### ISSUE TITLE
Replace: 'OldLabel' in Forgot Password E-mail

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#1]
**1. Subject line:**
please replace 
> Reseteaza parola Voluntari Gov IT Hub 

with

> Resetează parola de Voluntar CivicTechRo

**2. Logo**
please delete GovITHub logo (.jpg)

**3. Email text**
please replace current forgot password e-mail text:

> ai cerut resetarea parolei tale la Voluntari Gov IT Hub?
> Daca ai cerut resetarea parolei tale la voluntari.ithub.gov.ro folosind adresa de email __________ atunci foloseste butonul de mai jos pentru a finaliza procedura de resetare.
> Reseteaza Parola

with 

> Ai cerut resetarea parolei tale pentru platforma **Voluntari CivicTechRo**?

> Daca ai cerut resetarea parolei tale pentru a accesa [membri.civictech.ro](url) cu adresa de email ___ atunci folosește butonul de mai jos pentru a finaliza procedura de resetare.

> Resetează Parola

**4. Email footer**
please replace 
> Acest email este trimis de echipa Gov IT Hub

with 

> Acest email este trimis de echipa CivicTech România

__
![reseteaza parola voluntari gov it hub ligia adam gmail com gmail](https://cloud.githubusercontent.com/assets/22675754/26727901/0dc99318-47b1-11e7-98a8-c49ea6c394a4.png)

**Comment by dan-barbulescu** [comment]
The link the logo directs you to and the reset password link should point to the new domain (membri.civictech.ro)

**Comment by cezarneaga** [comment]
fixed by 31f594573186b888af231f966ddaa94c302249ed
