### ISSUE TITLE
Update: Meniu>>Status

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#10]
**Meniu: Status**

**1. Clean Up: Status Reports**
URL: https://membri.civictech.ro/status-reports 
- de sters tot
<img width="607" alt="status" src="https://cloud.githubusercontent.com/assets/22675754/26731420/bd80f048-47bc-11e7-91d1-86c431c803b3.png">

**2. Clean Up: Intalniri**
URL: https://membri.civictech.ro/meetings 
- de sters tot
![meetings](https://cloud.githubusercontent.com/assets/22675754/26731548/1568e1da-47bd-11e7-87d3-24a12f97570e.png)

**3. Update: Adauga Intalnire**
 -> de sters: 
Participanti: 
> Participanti din afara GovITHub

-> de corectat:
din
> Participant GovITHub

in

> Reprezentant CivicTechRo

-> de corectat:

> Adauga Bursier

in

> Adaugă membru CivicTechRo

-> de sters:

> Attn. Coordinatori
__

![gov it hub intalniri](https://cloud.githubusercontent.com/assets/22675754/26731769/c3c2b86e-47bd-11e7-8a1f-e6acbdb86f9a.png)

**Comment by cezarneaga** [comment]
Done
