### ISSUE TITLE
Mail confirmare Cont Nou

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#12]
de setat mailul automat pe care-l primesc cei care au completat formularului de Join VOLUNTAR de pe site-ul Civictech.ro (Feel free to make any edits).

__

Bine ai venit în comunitatea CivicTech România!

Te invităm să îți creezi o parolă pentru contul de utilizator <%= @user.email %> 
în [VoluntApp](www.membri.civictech.ro), platforma de management al membrilor <span class="brand-name">CivicTech<sup>RO</sup></span>

Și te așteptăm cât mai repede pe [Slack](civictech.now.sh) să ne cunoaștem!

Pe curând!
Echipa <span class="brand-name">CivicTech<sup>RO</sup></span>

**Comment by cezarneaga** [comment]
ia vezi acum: https://test.civictech.ro/rails/mailers/user/welcome.html

**Comment by cezarneaga** [comment]
Done

**Comment by LigiaAdam** [comment]
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.18 (Ubuntu) Server at test.civictech.ro Port 443
