### ISSUE TITLE
De adaugat -> Documente 

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#13]
De adaugat in VoluntApp /Documente

- Contractul de Voluntariat
- Acordul de Confidențialitate
[Acord de Confidențialitate [CivicTechRo].pdf](https://github.com/civictechro/volunt-app/files/1143109/Acord.de.Confiden.ialitate.CivicTechRo.pdf)
[Contract de Voluntariat [CivicTechRo].pdf](https://github.com/civictechro/volunt-app/files/1143135/Contract.de.Voluntariat.CivicTechRo.pdf)

**Comment by cezarneaga** [comment]
Done
