### ISSUE TITLE
Welcome Screen Update

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#14]
**Current text:**

Inscrie-te in comunitatea CivicTechRo!

**De inlocuit cu**

**Înscrie-te în comunitatea CivicTech România!**

Ca să poți accesa platforma de membri din Comunitatea <span class="brand-name">CivicTech<sup>RO</sup></span> te invităm să completezi mai întâi formularul de înregistrare disponibil pe site-ul [www.civictech.ro.](https://civictech.ro/hai-si-tu/) Te așteptăm alături de noi!

**Comment by cezarneaga** [comment]
done
