### ISSUE TITLE
CivicTechRO styling in footer

### ISSUE THREAD

**Issue by lucianstuparu** [civictechro/volunt-app#16]
CivicTechRO needs to be replaced with **civictech**ᴿᴼ in member's area footer.
![voluntapp-footer](https://user-images.githubusercontent.com/10770851/28238754-58ca08e2-6963-11e7-88bf-db173470ed57.png)

**Comment by ionutpopacivictech** [comment]
De evitat "ca sa" mai ales cand incepi o fraza (conjunctie compusa care introduce o subordonata; dar sa evitam acum gramatica, ca nu-i timp).
De inlocuit  in textul din screenshot "ca sa" cu "Pentru a putea..."

**Comment by cezarneaga** [comment]
fixed.
