### ISSUE TITLE
Afisare Meniu VoluntApp dupa SignUp Voluntar 

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#18]

**Comment by cezarneaga** [comment]
Cum ai ajuns sa gasesti bugul?

**Comment by LigiaAdam** [comment]
am urmat flow-ul de Sign Up de pe Site, cu alta adresa de mail

**Comment by cezarneaga** [comment]
Si daca dai refresh se intampla ceva diferit? Da-mi user parola pe mail te rog

**Comment by LigiaAdam** [comment]
nu se intampla nimic la refresh, nici nu pot sa ma deloghez ca sa ma loghez din nou.
Daca intru pe membri.civictech.ro imi face redirect automat la https://membri.civictech.ro/voluntari/1847

ligia.adam@outlook.com
pass: IntenseLife13!

**Comment by cezarneaga** [comment]
fixed
