### ISSUE TITLE
Issue Creare Cont Nou

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#19]
Dupa completarea formularului de pe site se creeaza user-ul

Dar:
- dupa aia se blocheaza VoluntApp 
- nu se mai afiseaza meniul sau posibilitatea de LogOut
- Nu merge logarea cu username-ul creat, dar merge sa-ti schimbi parola

**Comment by LigiaAdam** [comment]
dupa ce dai Forgot Password si dupa ce schimbi parola e totul ok

**Comment by cezarneaga** [comment]
fixed
