### ISSUE TITLE
Update: Old Header & Footer

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#3]
**1. Header: Logo GovITHUb**
- de sters
- va trebui inlocuit in curand

**2. Footer: GitHub Link**
- de inlocuit url actual cu https://github.com/civictechro

___
<img width="783" alt="untitled" src="https://cloud.githubusercontent.com/assets/22675754/26730015/3b9ac13e-47b8-11e7-9fa0-838dbb8a6007.png">

**Comment by cezarneaga** [comment]
closed with #2
