### ISSUE TITLE
CleanUp: OldFellows

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/volunt-app#4]
Issues @ https://membri.civictech.ro/fellows 

**1. Rename **Menu: Profile>Bursieri****

> Menu: Profile>Bursieri

to 

> Profile>Fondatori

**2. Rename current URL**

> Url: https://membri.civictech.ro/fellows 

with

> URL: https://membri.civictech.ro/fondatori

**3. Delete / Update OldTeam**
- de sters: 2, 4, 7, 9, 10, 13, 14, 15, 16, 18, 19
- update @civictech.ro email address pt 1, 3, 5, 6, 8, 11, 12, 17

**4. Update Add Bursier button**
- replace 

> Adaugă Bursier 

with 

> Adaugă Membru Asociat

___
<img width="641" alt="hg" src="https://cloud.githubusercontent.com/assets/22675754/26729984/24e60f0c-47b8-11e7-8b98-f87a9343fb03.png">

**Comment by cezarneaga** [comment]
Nu as vrea sa facem o distinctie intre membri in felul asta. Adica nu as pune `fondatori` ci doar `membri`.
iar momentan as scoate `coordonatori`.
